version: '3.8'

services:
  est-mit-web:
    build:
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./EST.MIT.Web:/home/dotnet/EST.MIT.Web
      - ./EST.MIT.Web.Test:/home/dotnet/EST.MIT.Web.Test